//
// Autogenerated by Laurine - by Jiri Trecak ( http://jiritrecak.com, @jiritrecak )
// Do not change this file manually!
//


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Imports

import Foundation


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Localizations


public struct Localizations {


    public struct Generic {

        /// Base translation: Ok
        public static var Ok : String = NSLocalizedString("Generic.Ok", tableName: nil, bundle: Bundle.main, value: "", comment: "")

        /// Base translation: No
        public static var No : String = NSLocalizedString("Generic.No", tableName: nil, bundle: Bundle.main, value: "", comment: "")

        /// Base translation: Yes
        public static var Yes : String = NSLocalizedString("Generic.Yes", tableName: nil, bundle: Bundle.main, value: "", comment: "")

    }
}
